# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:31
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mothers_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('sus', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('remedio', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('cx', 'cx')], max_length=2, null=True)),
                ('pills', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('remedio', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(null=True)),
                ('quantity_unit', models.CharField(blank=True, choices=[('mg', 'mg'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('cx', 'cx')], max_length=2, null=True)),
                ('pills', models.IntegerField()),
                ('doctor', models.CharField(max_length=150)),
                ('crm', models.CharField(max_length=10)),
                ('prescription', models.FileField(upload_to=core.models.prescription_file_upload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('razao_social', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
